version: "3"
services:

  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGODB_USER="root" 
      - MONGODB_PASS="root"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db-data:/data/db:/data/db
    networks:
      - backend
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  
  worker:
    env_file: .env
    image: ./
    volumes:
      - $(pwd):/app
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  backend:

volumes:
  db-data: