version: "3"
services:
  sshd:
    container_name: wdw_ssh
    image: maltyxx/sshd
    volumes:
        - ${SSH_ROOT}:/share
    networks:
      - backend
    ports:
        - "${SSH_PORT}:22"
    command: ${SSH_USER}:${SSH_PASS}:1001:1001
  db:
    container_name: wdw_db
    image: mongo:latest
    env_file: .env
    volumes:
      - db-data:/data/db
    networks:
      - backend
    ports:
        - ${DB_PORT}:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  
  worker:
    container_name: wdw_worker
    env_file: .env
    build: ./
    ports:
      - "${WORKER_PORT}:3000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data: